import os
import math
import time

# Start of the operating system

def STARTOS():
    os.system("title OpticOS 1.0.1")
    os.system("cls")
    time.sleep(0.1)
    print()
    print()
    print("     ")
    print("    O")
    print("    O")
    print("    O")
    print("     ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     O")
    print("    O ")
    print("    O ")
    print("    O ")
    print("     O")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OO")
    print("    O  ")
    print("    O  ")
    print("    O  ")
    print("     OO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOO")
    print("    O   ")
    print("    O   ")
    print("    O   ")
    print("     OOO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOO")
    print("    O    ")
    print("    O    ")
    print("    O    ")
    print("     OOOO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO")
    print("    O     ")
    print("    O     ")
    print("    O     ")
    print("     OOOOO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO ")
    print("    O     O")
    print("    O     O")
    print("    O     O")
    print("     OOOOO ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO  ")
    print("    O     O ")
    print("    O     O ")
    print("    O     O ")
    print("     OOOOO  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   ")
    print("    O     O  ")
    print("    O     O  ")
    print("    O     O  ")
    print("     OOOOO   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   P")
    print("    O     O  P")
    print("    O     O  P")
    print("    O     O  P")
    print("     OOOOO   P")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PP")
    print("    O     O  P ")
    print("    O     O  PP")
    print("    O     O  P ")
    print("     OOOOO   P ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPP")
    print("    O     O  P  ")
    print("    O     O  PPP")
    print("    O     O  P  ")
    print("     OOOOO   P  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP")
    print("    O     O  P   ")
    print("    O     O  PPPP")
    print("    O     O  P   ")
    print("     OOOOO   P   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP ")
    print("    O     O  P   P")
    print("    O     O  PPPP ")
    print("    O     O  P    ")
    print("     OOOOO   P    ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP  ")
    print("    O     O  P   P ")
    print("    O     O  PPPP  ")
    print("    O     O  P     ")
    print("     OOOOO   P     ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   ")
    print("    O     O  P   P  ")
    print("    O     O  PPPP   ")
    print("    O     O  P      ")
    print("     OOOOO   P      ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   T")
    print("    O     O  P   P   ")
    print("    O     O  PPPP    ")
    print("    O     O  P       ")
    print("     OOOOO   P       ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TT")
    print("    O     O  P   P    ")
    print("    O     O  PPPP     ")
    print("    O     O  P        ")
    print("     OOOOO   P        ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTT")
    print("    O     O  P   P    T")
    print("    O     O  PPPP     T")
    print("    O     O  P        T")
    print("     OOOOO   P        T")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTT")
    print("    O     O  P   P    T ")
    print("    O     O  PPPP     T ")
    print("    O     O  P        T ")
    print("     OOOOO   P        T ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT")
    print("    O     O  P   P    T  ")
    print("    O     O  PPPP     T  ")
    print("    O     O  P        T  ")
    print("     OOOOO   P        T  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT ")
    print("    O     O  P   P    T   ")
    print("    O     O  PPPP     T   ")
    print("    O     O  P        T   ")
    print("     OOOOO   P        T   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  ")
    print("    O     O  P   P    T    ")
    print("    O     O  PPPP     T    ")
    print("    O     O  P        T    ")
    print("     OOOOO   P        T    ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I")
    print("    O     O  P   P    T     ")
    print("    O     O  PPPP     T    I")
    print("    O     O  P        T    I")
    print("     OOOOO   P        T    I")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I ")
    print("    O     O  P   P    T      ")
    print("    O     O  PPPP     T    I ")
    print("    O     O  P        T    I ")
    print("     OOOOO   P        T    I ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I  ")
    print("    O     O  P   P    T       ")
    print("    O     O  PPPP     T    I  ")
    print("    O     O  P        T    I  ")
    print("     OOOOO   P        T    I  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   ")
    print("    O     O  P   P    T       C")
    print("    O     O  PPPP     T    I  C")
    print("    O     O  P        T    I  C")
    print("     OOOOO   P        T    I   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   C")
    print("    O     O  P   P    T       C ")
    print("    O     O  PPPP     T    I  C ")
    print("    O     O  P        T    I  C ")
    print("     OOOOO   P        T    I   C")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CC")
    print("    O     O  P   P    T       C  ")
    print("    O     O  PPPP     T    I  C  ")
    print("    O     O  P        T    I  C  ")
    print("     OOOOO   P        T    I   CC")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCC")
    print("    O     O  P   P    T       C   ")
    print("    O     O  PPPP     T    I  C   ")
    print("    O     O  P        T    I  C   ")
    print("     OOOOO   P        T    I   CCC")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCC")
    print("    O     O  P   P    T       C    ")
    print("    O     O  PPPP     T    I  C    ")
    print("    O     O  P        T    I  C    ")
    print("     OOOOO   P        T    I   CCCC")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC")
    print("    O     O  P   P    T       C     ")
    print("    O     O  PPPP     T    I  C     ")
    print("    O     O  P        T    I  C     ")
    print("     OOOOO   P        T    I   CCCCC")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC ")
    print("    O     O  P   P    T       C      ")
    print("    O     O  PPPP     T    I  C      ")
    print("    O     O  P        T    I  C      ")
    print("     OOOOO   P        T    I   CCCCC ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC  ")
    print("    O     O  P   P    T       C       ")
    print("    O     O  PPPP     T    I  C       ")
    print("    O     O  P        T    I  C       ")
    print("     OOOOO   P        T    I   CCCCC  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC   ")
    print("    O     O  P   P    T       C        ")
    print("    O     O  PPPP     T    I  C        ")
    print("    O     O  P        T    I  C        ")
    print("     OOOOO   P        T    I   CCCCC   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC    ")
    print("    O     O  P   P    T       C         ")
    print("    O     O  PPPP     T    I  C         ")
    print("    O     O  P        T    I  C         ")
    print("     OOOOO   P        T    I   CCCCC    ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     ")
    print("    O     O  P   P    T       C         O")
    print("    O     O  PPPP     T    I  C         O")
    print("    O     O  P        T    I  C         O")
    print("     OOOOO   P        T    I   CCCCC     ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     O")
    print("    O     O  P   P    T       C         O ")
    print("    O     O  PPPP     T    I  C         O ")
    print("    O     O  P        T    I  C         O ")
    print("     OOOOO   P        T    I   CCCCC     O")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OO")
    print("    O     O  P   P    T       C         O  ")
    print("    O     O  PPPP     T    I  C         O  ")
    print("    O     O  P        T    I  C         O  ")
    print("     OOOOO   P        T    I   CCCCC     OO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOO")
    print("    O     O  P   P    T       C         O   ")
    print("    O     O  PPPP     T    I  C         O   ")
    print("    O     O  P        T    I  C         O   ")
    print("     OOOOO   P        T    I   CCCCC     OOO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOO")
    print("    O     O  P   P    T       C         O    ")
    print("    O     O  PPPP     T    I  C         O    ")
    print("    O     O  P        T    I  C         O    ")
    print("     OOOOO   P        T    I   CCCCC     OOOO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO")
    print("    O     O  P   P    T       C         O     ")
    print("    O     O  PPPP     T    I  C         O     ")
    print("    O     O  P        T    I  C         O     ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO ")
    print("    O     O  P   P    T       C         O     O")
    print("    O     O  PPPP     T    I  C         O     O")
    print("    O     O  P        T    I  C         O     O")
    print("     OOOOO   P        T    I   CCCCC     OOOOO ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO  ")
    print("    O     O  P   P    T       C         O     O ")
    print("    O     O  PPPP     T    I  C         O     O ")
    print("    O     O  P        T    I  C         O     O ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO   ")
    print("    O     O  P   P    T       C         O     O  ")
    print("    O     O  PPPP     T    I  C         O     O  ")
    print("    O     O  P        T    I  C         O     O  ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    ")
    print("    O     O  P   P    T       C         O     O  S")
    print("    O     O  PPPP     T    I  C         O     O   ")
    print("    O     O  P        T    I  C         O     O   ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    S")
    print("    O     O  P   P    T       C         O     O  S ")
    print("    O     O  PPPP     T    I  C         O     O   S")
    print("    O     O  P        T    I  C         O     O    ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    S")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SS")
    print("    O     O  P   P    T       C         O     O  S  ")
    print("    O     O  PPPP     T    I  C         O     O   SS")
    print("    O     O  P        T    I  C         O     O     ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SS")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSS")
    print("    O     O  P   P    T       C         O     O  S   ")
    print("    O     O  PPPP     T    I  C         O     O   SSS")
    print("    O     O  P        T    I  C         O     O      ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSS")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSS")
    print("    O     O  P   P    T       C         O     O  S    ")
    print("    O     O  PPPP     T    I  C         O     O   SSSS")
    print("    O     O  P        T    I  C         O     O       ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSS")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS")
    print("    O     O  P   P    T       C         O     O  S     ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS")
    print("    O     O  P        T    I  C         O     O        ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS ")
    print("    O     O  P   P    T       C         O     O  S      ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS ")
    print("    O     O  P        T    I  C         O     O        S")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS  ")
    print("    O     O  P   P    T       C         O     O  S       ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS  ")
    print("    O     O  P        T    I  C         O     O        S ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS   ")
    print("    O     O  P   P    T       C         O     O  S        ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS   ")
    print("    O     O  P        T    I  C         O     O        S  ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS    ")
    print("    O     O  P   P    T       C         O     O  S         ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    ")
    print("    O     O  P        T    I  C         O     O        S   ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS    ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS     ")
    print("    O     O  P   P    T       C         O     O  S          ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1")
    print("    O     O  P        T    I  C         O     O        S    ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS     ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      ")
    print("    O     O  P   P    T       C         O     O  S          1")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 ")
    print("    O     O  P        T    I  C         O     O        S     ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1")
    print("    O     O  P   P    T       C         O     O  S          11")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1")
    print("    O     O  P        T    I  C         O     O        S     1")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1 ")
    print("    O     O  P   P    T       C         O     O  S          11 ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1 ")
    print("    O     O  P        T    I  C         O     O        S     1 ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1  ")
    print("    O     O  P   P    T       C         O     O  S          11  ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1  ")
    print("    O     O  P        T    I  C         O     O        S     1  ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1   ")
    print("    O     O  P   P    T       C         O     O  S          11   ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   ")
    print("    O     O  P        T    I  C         O     O        S     1   ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @ ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    ")
    print("    O     O  P   P    T       C         O     O  S          11   0")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0")
    print("    O     O  P        T    I  C         O     O        S     1   0")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    0")
    print("    O     O  P   P    T       C         O     O  S          11   0 ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0 ")
    print("    O     O  P        T    I  C         O     O        S     1   0 ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  0")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    00")
    print("    O     O  P   P    T       C         O     O  S          11   0  ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0  ")
    print("    O     O  P        T    I  C         O     O        S     1   0  ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  00")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000")
    print("    O     O  P   P    T       C         O     O  S          11   0   ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   ")
    print("    O     O  P        T    I  C         O     O        S     1   0   ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000 ")
    print("    O     O  P   P    T       C         O     O  S          11   0   0")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0")
    print("    O     O  P        T    I  C         O     O        S     1   0   0")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000 ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000  ")
    print("    O     O  P   P    T       C         O     O  S          11   0   0 ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0 ")
    print("    O     O  P        T    I  C         O     O        S     1   0   0 ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000   ")
    print("    O     O  P   P    T       C         O     O  S          11   0   0  ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0  ")
    print("    O     O  P        T    I  C         O     O        S     1   0   0  ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000  @")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000    ")
    print("    O     O  P   P    T       C         O     O  S          11   0   0   ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0   ")
    print("    O     O  P        T    I  C         O     O        S     1   0   0   ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000  @ ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000     ")
    print("    O     O  P   P    T       C         O     O  S          11   0   0    ")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0   1")
    print("    O     O  P        T    I  C         O     O        S     1   0   0    ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000  @  ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000      ")
    print("    O     O  P   P    T       C         O     O  S          11   0   0    1")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0   1 ")
    print("    O     O  P        T    I  C         O     O        S     1   0   0     ")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000  @   ")
    time.sleep(0.05)
    os.system("cls")
    print()
    print()
    print("     OOOOO   PPPP   TTTTT  I   CCCCC     OOOOO    SSSSS      1    000      1")
    print("    O     O  P   P    T       C         O     O  S          11   0   0    11")
    print("    O     O  PPPP     T    I  C         O     O   SSSSS    1 1   0   0   1 1")
    print("    O     O  P        T    I  C         O     O        S     1   0   0     1")
    print("     OOOOO   P        T    I   CCCCC     OOOOO    SSSSS      1 @  000  @   1")
    time.sleep(2)
    print()
    print("    Hello World!")
    print()
    print("    Welcome to OpticOS! :)")
    print()
    print()
    os.system("pause")

STARTOS()

while True:
    while True:
        try:
            os.system("cls")
            program_gain=input("What u wana do : ")
            program=int(program_gain)
            os.system("cls")
            break
        except ValueError:
            os.system("cls")
            print("Please provide an intiger in order for the program to run accordingly.")
            print()
            if program_gain=="":
                print("User input: <blank>")
            else:
                print("User input:", program_gain)
            print()
            print()
            os.system("pause")
        except Exception as e:
            os.system("cls")
            print(f"An unexpected error has occured: {e}")
            print()
            os.system("pause")
    if program<0:
        print("Bro we not in the negatives.")
        print()
        os.system("pause")
    elif program==0:
        print("Wow u typed 0.")
        print()
        os.system("pause")
    elif program==1:
        print("1")
        print()
        os.system("pause")
    elif program==2:
        print("Closing. Bye bye :)")
        time.sleep(2)
        exit()
    elif program==3:
        STARTOS()
    else:
        print("Bro we not that high yet.")
        print()
        os.system("pause")